import { 
  IconReact, 
  IconTailwind, 
  IconNodeJs, 
  IconExpressJs, 
  IconMongoDB, 
  IconFirebase,
  IconJWT,
  IconStripe,
  IconTanstackQuery,
  IconAxios,
  IconLeaflet,
  IconReactRouter,
  IconGit,
  IconExternalLink,
  IconDetails,
} from '../components/Icons.jsx';

export const PROJECTS = [
  {
    title: 'CourtNest',
    category: 'Full-Stack',
    description: 'CourtNest is a full-stack role-based court booking web application with secure Stripe payments, dynamic dashboards, and location-based court listings.',
    imageUrl: 'https://picsum.photos/seed/court/800/600',
    tags: [
      { name: 'React', icon: IconReact() },
      { name: 'Tailwind CSS', icon: IconTailwind() },
      { name: 'React Router', icon: IconReactRouter() },
      { name: 'Firebase', icon: IconFirebase() },
      { name: 'Stripe', icon: IconStripe() },
      { name: 'NodeJs', icon: IconNodeJs() },
      { name: 'ExpressJs', icon: IconExpressJs() },
      { name: 'MongoDB', icon: IconMongoDB() },
      { name: 'JWT', icon: IconJWT() },
      { name: 'TanStack Query', icon: IconTanstackQuery() },
      { name: 'Axios', icon: IconAxios() },
      { name: 'Leaflet', icon: IconLeaflet() },
    ],
    links: [
      { label: 'View Project', url: '#', icon: IconExternalLink() },
      { label: 'Git Client', url: '#', icon: IconGit() },
      { label: 'Git Server', url: '#', icon: IconGit() },
      { label: 'See Details', url: '#', icon: IconDetails() },
    ],
  },
  {
    title: 'EcoFridge',
    category: 'Full-Stack',
    description: 'EcoFridge is a web application that helps users track food items, receive expiry alerts, and reduce food waste. Built for a greener tomorrow.',
    imageUrl: 'https://picsum.photos/seed/eco/800/600',
    tags: [
      { name: 'React', icon: IconReact() },
      { name: 'Tailwind', icon: IconTailwind() },
      { name: 'NodeJs', icon: IconNodeJs() },
      { name: 'ExpressJs', icon: IconExpressJs() },
      { name: 'MongoDB', icon: IconMongoDB() },
      { name: 'Firebase', icon: IconFirebase() },
      { name: 'JWT', icon: IconJWT() },
    ],
    links: [
      { label: 'View Project', url: '#', icon: IconExternalLink() },
      { label: 'Git Client', url: '#', icon: IconGit() },
      { label: 'Git Server', url: '#', icon: IconGit() },
      { label: 'See Details', url: '#', icon: IconDetails() },
    ],
  },
  {
    title: 'kajKori',
    category: 'Full-Stack',
    description: 'kajKori is a modern freelance task marketplace platform designed to connect individuals seeking small tasks with skilled freelancers ready to offer their services.',
    imageUrl: 'https://picsum.photos/seed/freelance/800/600',
    tags: [
      { name: 'React', icon: IconReact() },
      { name: 'Tailwind', icon: IconTailwind() },
      { name: 'NodeJs', icon: IconNodeJs() },
      { name: 'ExpressJs', icon: IconExpressJs() },
      { name: 'MongoDB', icon: IconMongoDB() },
      { name: 'Firebase', icon: IconFirebase() },
    ],
    links: [
      { label: 'View Project', url: '#', icon: IconExternalLink() },
      { label: 'Git Client', url: '#', icon: IconGit() },
      { label: 'Git Server', url: '#', icon: IconGit() },
      { label: 'See Details', url: '#', icon: IconDetails() },
    ],
  },
    {
    title: 'Artisan',
    category: 'Front-End',
    description: 'A beautiful gallery and portfolio for artists and designers to showcase their work with a clean, minimal, and modern aesthetic.',
    imageUrl: 'https://picsum.photos/seed/artisan/800/600',
    tags: [
      { name: 'React', icon: IconReact() },
      { name: 'Tailwind', icon: IconTailwind() },
      { name: 'React Router', icon: IconReactRouter() },
      { name: 'Firebase', icon: IconFirebase() },
    ],
    links: [
      { label: 'View Project', url: '#', icon: IconExternalLink() },
      { label: 'Git Client', url: '#', icon: IconGit() },
      { label: 'See Details', url: '#', icon: IconDetails() },
    ],
  },
];